### ISSUE TITLE
Java 9+ support

### ISSUE THREAD

**Issue by gahag** [adobe/ride#55]
### Expected Behaviour
When using java 9 or bigger, all tests pass

### Actual Behaviour
When using java 9 or bigger, one test fails due to a NPE related to the ClassLoader.

### Reproduce Scenario (including but not limited to)
Java 10 setup.

#### Steps to Reproduce
Run the tests on the develop branch.

#### Logs taken while reproducing problem
> Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.565 sec <<< FAILURE!
> testStringJsonSchema(com.adobe.ride.utilities.model.test.ModelObjectTest)  Time elapsed: 0.003 sec  <<< FAILURE!
> java.lang.NullPointerException
>         at java.base/java.io.Reader.<init>(Reader.java:167)
>         at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:113)
>         at org.apache.commons.io.IOUtils.copy(IOUtils.java:2272)
>         at org.apache.commons.io.IOUtils.toString(IOUtils.java:1041)
>         at com.adobe.ride.utilities.model.test.ModelObjectTest.testStringJsonSchema(ModelObjectTest.java:94)

**Comment by gahag** [comment]
@tedcasey hey, I've been very busy lately, but found some time to dig further into this. I've made a dockerfile to test this issue, and after testing with openjdk 8, 9, 10 and 13, I can confirm the ClassLoader issue occurs with version 9 or bigger. I can supply the dockerfile if you'd like to test it too. I believe the fix would be to apply the change we've dismissed [here](https://github.com/adobe/ride/pull/53#discussion_r335699727). What do you think?
